// app/components/Header.vue
<script setup lang="ts">
import AuthModal from "~/components/modals/AuthModal.vue";
import WideBurger from "~/components/dropdowns/WideBurger.vue";
import UnderConstruction from "~/components/header/UnderConstruction.vue";
import MobileBurger from "~/components/dropdowns/MobileBurger.vue";

const viewport = useViewport()
watch(viewport.breakpoint, (newBreakpoint, oldBreakpoint) => {
  console.log('Breakpoint updated:', oldBreakpoint, '->', newBreakpoint)
})


const links = [
  {
    text: "FAQ",
    href: "/faq",
  },
  {
    text: "Applications",
    href: "/apps",
  },
  {
    text: "API",
    href: "/docs",
  },
  {
    text: "Feedbacks",
    href: "/feedbacks",
  }
]
</script>

<template>
  <header class="header flex flex-col w-full fixed">
    <div class="header-container h-12 flex items-center bg-white dark:bg-neutral-950 border-b border-gray-300 dark:border-neutral-700 px-4 justify-between">
      <div class="left flex items-center h-full gap-2">
        <div class="logo">
          <LazyNuxtLink class="font-black text-xl text-black dark:text-white" href="/">
            FLUENT
          </LazyNuxtLink>
        </div>
        <div v-if="viewport.isGreaterThan('mobileWide')" class="links items-center gap-1 flex">
          <LazyNuxtLink v-for="(link, id) in links" :key="id" class="text-sm text-neutral-800 dark:text-neutral-400 hover:text-neutral-600 dark:hover:text-neutral-300 duration-100" :href="link.href">
            {{ link.text }}
          </LazyNuxtLink>
        </div>
      </div>
      <div v-if="viewport.isGreaterThan('mobileWide')" class="right flex items-center h-full gap-2">
        <WideBurger />
        <AuthModal />
      </div>
      <div v-else class="right flex items-center h-full gap-2">
        <MobileBurger />
        <AuthModal />
      </div>
    </div>
  <UnderConstruction />
  </header>
</template>

<style scoped>

</style>

// src/app/components/Header.tsx
import Link from "next/link";

import gsap from "gsap";
// import {useGSAP} from "@gsap/react";
// import {useRef} from "react";

export default function Header() {

    const links = [
        {
            id: 1,
            text: "FAQ",
            href: "/faq",
        },
        {
            id: 2,
            text: "Applications",
            href: "/apps",
        },
        {
            id: 3,
            text: "API",
            href: "/docs",
        }
    ]


    return (
        <header className={"header w-full flex justify-center"}>
            <div className="header-container w-full max-w-[1200px] mx-auto h-20 flex items-center justify-between">
                <div className="left links flex gap-4 h-16">
                    <div className="logo flex items-center w-24">
                        <Link className="link text-neutral-900 flex items-center my-auto font-extrabold text-2xl" href={""}>Fluent</Link>
                    </div>
                    <ul className="links flex items-center gap-3 text-sm text-gray-500">
                        {
                            links.map(link =>
                            <li>
                                <Link className="link text-neutral-500 flex items-center hover:text-gray-700 duration-100" key={link.id} href={link.href}>
                                    {link.text}
                                </Link>
                            </li>
                            )
                        }
                    </ul>
                </div>
                <div className="right auth flex gap-4">
                    <Link href={"signin"}
                          className="btn signin flex border font-semibold tracking-wide text-sm border-neutral-300 items-center justify-center w-18 h-8 rounded-md hover:bg-slate-200/60">Sign In</Link>
                    <Link href={"signup"} className="btn signup font-semibold tracking-wide text-sm flex border border-neutral-950 bg-neutral-950 text-white w-18 h-8 items-center justify-center rounded-md">Sign Up</Link>
                </div>
            </div>
        </header>
    );
}
